In [1]:
# !pip install sentence-transformers

In [2]:
# Image to vector
from sentence_transformers import SentenceTransformer
from PIL import Image

img_model = SentenceTransformer("clip-ViT-B-32")
images = [Image.open("./bird.jpg")]
embeddings = img_model.encode(images)
embeddings

c:\Users\sudhy\.conda\envs\capstoneProject\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


array([[-7.86185265e-04,  1.54045910e-01, -7.69710541e-02,
        -3.26521844e-01, -3.76895279e-01,  3.12635958e-01,
         4.51422304e-01,  8.37561935e-02,  1.78676575e-01,
         2.97791988e-01,  1.27973035e-01,  2.87928015e-01,
        -1.81636050e-01, -8.78611505e-02, -5.31834960e-02,
         2.13372380e-01,  6.28665924e-01,  2.69034415e-01,
         1.04802251e-01, -1.12204425e-01,  1.50420815e-01,
        -4.70350981e-02, -4.20310408e-01, -1.24978572e-02,
        -8.89795780e-01,  3.53749663e-01, -3.16307172e-02,
        -1.21108949e-01,  2.06321359e-01,  1.03361264e-01,
         1.23982526e-01,  3.36317599e-01, -5.70594370e-02,
         1.34541273e-01,  2.83238471e-01,  2.62069136e-01,
         2.59467363e-01,  2.30931327e-01,  3.54387224e-01,
         1.13405406e+00,  5.02618194e-01,  4.10443544e-01,
        -2.40440309e-01, -8.00407290e-01,  3.61183167e-01,
        -9.93780673e-01,  1.79815009e-01,  4.96173859e-01,
         2.88946718e-01,  2.15569481e-01, -8.10957998e-0

In [3]:
from sentence_transformers import SentenceTransformer

# Load the pre-trained model
text_model = SentenceTransformer("clip-ViT-B-32")

# Encode the text into vectors
text = "elephant in a forest"
ele = text_model.encode(text)
print(ele)

# Encode the text into vectors
text = ["a photo of a bird"]
bird = text_model.encode(text)
print(bird)

[-6.37164563e-02 -5.66688329e-02 -9.75903273e-02  3.79085213e-01
  5.98160923e-03 -8.09138119e-02 -6.84479594e-01 -4.78194594e-01
 -4.97180670e-01 -6.38172030e-03 -6.88737854e-02 -1.34401023e-01
 -2.21338794e-01 -1.85119405e-01 -7.43692815e-02 -3.67344022e-02
  1.75816059e-01  1.12534605e-01 -1.60974711e-01  5.05757272e-01
  1.95076749e-01  7.53777027e-01  1.88528016e-01  1.02092519e-01
 -1.80797130e-01  3.00202698e-01 -2.01812536e-01  4.15316284e-01
  1.44199699e-01  2.76710451e-01 -1.08551636e-01  5.02184778e-03
 -2.03222349e-01  7.69247860e-02 -1.11071482e-01  1.13992006e-01
  1.50575623e-01  2.93360829e-01 -5.05027533e-01 -5.02119958e-02
 -1.27813011e-01  1.57998413e-01  1.80500835e-01  1.12431020e-01
  3.02241325e-01  1.10401690e-01 -1.71301484e-01 -4.72524613e-02
  2.66174078e-01 -1.80502191e-01 -8.68669152e-03 -3.63519669e-01
 -2.71044195e-01 -9.59140211e-02 -1.28779352e-01 -3.55910718e-01
  1.22317165e-01  8.87381136e-02  3.62565130e-01  3.21949363e-01
  1.48199067e-01  1.83384

In [4]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Assuming text_embedding and embeddings are the vectors obtained from CLIP
# Reshape the text_embedding to have a single sample
text_embedding_reshaped = bird.reshape(1, -1)

# Calculate the similarity score
similarity_score = cosine_similarity(text_embedding_reshaped, embeddings)
print(similarity_score)



[[0.27873304]]


In [5]:
# Encode the text into vectors
text = "Image of a deer in a field"
gree = text_model.encode(text)


text_embedding_reshaped = gree.reshape(1, -1)

# Calculate the similarity score
similarity_score = cosine_similarity(text_embedding_reshaped, embeddings)
print(similarity_score)

[[0.12179847]]


In [6]:
# CLIP
from transformers import CLIPProcessor

clip_processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")


def clip_text_embeddings(text):
    inputs = clip_processor(text, return_tensors="pt", padding=True)
    input_tokens = {k: v for k, v in inputs.items()}

    return input_tokens["input_ids"]


# Example usage
text = "Image of a deer"
text_embeddings = clip_text_embeddings(text)
dee = text_embeddings
print(dee)



tensor([[49406,  2867,   539,   320,  8700, 49407]])


In [7]:
from transformers import AutoTokenizer, CLIPTextModelWithProjection

model = CLIPTextModelWithProjection.from_pretrained("openai/clip-vit-base-patch32")
tokenizer = AutoTokenizer.from_pretrained("openai/clip-vit-base-patch32")

inputs = tokenizer(["a photo of a bird"], padding=True, return_tensors="pt")

outputs = model(**inputs)
text_embeds = outputs.text_embeds
text_embeds

tensor([[ 2.3636e-01,  3.9309e-01, -8.1562e-02, -2.4629e-01, -1.7004e-01,
          3.3082e-02, -4.3361e-01, -9.6659e-01, -3.0025e-01,  2.3191e-01,
         -9.7653e-02, -4.5459e-01,  5.0889e-02,  1.0255e-01,  8.6047e-02,
          7.5476e-02,  3.1082e-01,  3.5262e-02, -1.9845e-01,  2.9195e-02,
          6.9721e-01, -6.7943e-02, -1.3253e-02,  2.9071e-01, -4.3458e-01,
          3.3267e-01,  2.3165e-01,  1.9502e-01, -2.4242e-01,  3.0305e-02,
          2.7919e-01,  3.3271e-01, -1.5987e-01,  4.3208e-01, -2.1738e-01,
         -4.5904e-02, -1.2354e-01, -1.3604e-01, -2.5567e-02,  3.6069e-01,
          3.1585e-02,  1.3602e-01,  1.6282e-01, -9.4308e-02,  6.1279e-01,
          8.7639e-02, -3.4950e-02,  1.4901e-01, -2.4843e-01, -4.7495e-02,
         -4.5912e-02, -3.1183e-01,  2.0313e-01, -4.3618e-01, -2.5661e-02,
         -3.6617e-02, -1.9577e-02,  1.4797e-01,  1.6580e-01,  2.3598e-01,
          5.6280e-01, -3.6255e-01, -3.4242e-01, -3.8552e-02,  1.2735e-01,
         -2.1974e-01, -4.7782e-02,  2.

In [8]:
from transformers import CLIPProcessor, CLIPModel
from PIL import Image
import torch


model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")


# Load and process the image
image = Image.open("./deer.jpg")
inputs = processor(text='dummy_input_ids', images=image, return_tensors="pt")

# Get the image embeddings
outputs = model(**inputs)
image_embeds = outputs
list(image_embeds)

['logits_per_image',
 'logits_per_text',
 'text_embeds',
 'image_embeds',
 'text_model_output',
 'vision_model_output']

In [9]:
from transformers import CLIPProcessor

clip_processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

image = Image.open("./bird.jpg")

inputs = clip_processor(images=image, return_tensors="pt", padding=True)
inputs['pixel_values']


tensor([[[[-0.0405, -0.0259, -0.0259,  ..., -0.0696, -0.1280, -0.1572],
          [-0.0696, -0.0259, -0.0259,  ..., -0.0842, -0.1134, -0.1572],
          [-0.0842, -0.0405, -0.0259,  ..., -0.0696, -0.1134, -0.1572],
          ...,
          [-0.5222, -0.5222, -0.5222,  ...,  1.7114,  1.9303,  1.9011],
          [-0.5660, -0.5806, -0.5660,  ...,  1.6238,  1.8573,  1.9011],
          [-0.6098, -0.5952, -0.5806,  ...,  1.8281,  1.7844,  1.8135]],

         [[ 0.6341,  0.6341,  0.6642,  ...,  0.3040,  0.2289,  0.1989],
          [ 0.6191,  0.6341,  0.6491,  ...,  0.3190,  0.2740,  0.2289],
          [ 0.6191,  0.6341,  0.6642,  ...,  0.3190,  0.2740,  0.2289],
          ...,
          [ 0.0188,  0.0338,  0.0338,  ...,  1.7447,  1.9848,  1.9548],
          [ 0.0038,  0.0338,  0.0188,  ...,  1.6547,  1.8948,  2.0149],
          [ 0.0038,  0.0038, -0.0112,  ...,  1.8348,  1.7897,  1.8648]],

         [[-0.8403, -0.8403, -0.8261,  ..., -0.4990, -0.4848, -0.4990],
          [-0.8545, -0.8261, -

In [10]:
import torch
from sklearn.metrics.pairwise import cosine_similarity

from transformers import AutoTokenizer, CLIPTextModelWithProjection

model = CLIPTextModelWithProjection.from_pretrained("openai/clip-vit-base-patch32")
tokenizer = AutoTokenizer.from_pretrained("openai/clip-vit-base-patch32")

inputs = tokenizer(["a photo of a sparrow"], padding=True, return_tensors="pt")

outputs = model(**inputs)
text_embeds = outputs.text_embeds
text_embeds


from transformers import CLIPProcessor, CLIPModel
from PIL import Image
import torch


model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")


# Load and process the image
image = Image.open("./deer.jpg")
inputs = processor(text='ids', images=image, return_tensors="pt")

# Get the image embeddings
outputs = model(**inputs)
image_embeds = outputs
list(image_embeds)


['logits_per_image',
 'logits_per_text',
 'text_embeds',
 'image_embeds',
 'text_model_output',
 'vision_model_output']

In [11]:
import torch
from sklearn.metrics.pairwise import cosine_similarity

# Normalize the text embedding vector
b_normalized = torch.nn.functional.normalize(text_embeds, p=2, dim=1)

# Get the image embeddings from the correct key in outputs
image_embeds = outputs['image_embeds']

# Normalize the image embedding vector
a_normalized = torch.nn.functional.normalize(image_embeds, p=2, dim=1)

# Calculate cosine similarity
similarity_score = cosine_similarity(a_normalized.cpu().detach().numpy(), b_normalized.cpu().detach().numpy())

print(f"Similarity score between the image and text vectors: {similarity_score[0][0]}")

Similarity score between the image and text vectors: 0.1735156774520874


In [12]:
from PIL import Image
import requests

from transformers import CLIPProcessor, CLIPModel

model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

url = "./bird.jpg"
image = Image.open(url)

inputs = processor(text=["a photo of a cat", "a photo of a dog",'a photo of a sparrow'], images=image, return_tensors="pt", padding=True)
list(inputs)
inputs['input_ids']

tensor([[49406,   320,  1125,   539,   320,  2368, 49407],
        [49406,   320,  1125,   539,   320,  1929, 49407],
        [49406,   320,  1125,   539,   320, 22888, 49407]])

In [13]:
type(inputs)

transformers.tokenization_utils_base.BatchEncoding

In [14]:

outputs = model(**inputs)
logits_per_image = outputs.logits_per_image  # this is the image-text similarity score
probs = logits_per_image.softmax(dim=1)  # we can take the softmax to get the label probabilities

In [15]:
list(probs)

[tensor([0.0236, 0.0251, 0.9512], grad_fn=<UnbindBackward0>)]

In [16]:
from PIL import Image
import requests

from transformers import CLIPProcessor, CLIPModel

model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

url = "./bird.jpg"
image = Image.open(url)

inputs1 = processor( images=image, return_tensors="pt", padding=True)

In [17]:
type(inputs1)

transformers.tokenization_utils_base.BatchEncoding

In [18]:
list(inputs1)
inputs1

{'pixel_values': tensor([[[[-0.0405, -0.0259, -0.0259,  ..., -0.0696, -0.1280, -0.1572],
          [-0.0696, -0.0259, -0.0259,  ..., -0.0842, -0.1134, -0.1572],
          [-0.0842, -0.0405, -0.0259,  ..., -0.0696, -0.1134, -0.1572],
          ...,
          [-0.5222, -0.5222, -0.5222,  ...,  1.7114,  1.9303,  1.9011],
          [-0.5660, -0.5806, -0.5660,  ...,  1.6238,  1.8573,  1.9011],
          [-0.6098, -0.5952, -0.5806,  ...,  1.8281,  1.7844,  1.8135]],

         [[ 0.6341,  0.6341,  0.6642,  ...,  0.3040,  0.2289,  0.1989],
          [ 0.6191,  0.6341,  0.6491,  ...,  0.3190,  0.2740,  0.2289],
          [ 0.6191,  0.6341,  0.6642,  ...,  0.3190,  0.2740,  0.2289],
          ...,
          [ 0.0188,  0.0338,  0.0338,  ...,  1.7447,  1.9848,  1.9548],
          [ 0.0038,  0.0338,  0.0188,  ...,  1.6547,  1.8948,  2.0149],
          [ 0.0038,  0.0038, -0.0112,  ...,  1.8348,  1.7897,  1.8648]],

         [[-0.8403, -0.8403, -0.8261,  ..., -0.4990, -0.4848, -0.4990],
          [-0

In [19]:
from PIL import Image
import requests

from transformers import CLIPProcessor, CLIPModel

model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

url = "./bird.jpg"
image = Image.open(url)

inputs = processor(text=['a photo of a tiger','a photo of man','a photo of car','a photo of sparrow','a photo of deer'], return_tensors="pt", padding=True)
list(inputs)

['input_ids', 'attention_mask']

In [20]:
type(inputs)

transformers.tokenization_utils_base.BatchEncoding

In [21]:
inputs

{'input_ids': tensor([[49406,   320,  1125,   539,   320,  6531, 49407],
        [49406,   320,  1125,   539,   786, 49407, 49407],
        [49406,   320,  1125,   539,  1615, 49407, 49407],
        [49406,   320,  1125,   539, 22888, 49407, 49407],
        [49406,   320,  1125,   539,  8700, 49407, 49407]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 0]])}

In [22]:
from transformers import BatchEncoding

# inputs1.update(inputs)

temp = inputs1
temp.update(inputs)

# print(inputs1)

outputs = model(**temp)
logits_per_image = outputs.logits_per_image  # this is the image-text similarity score
probs = logits_per_image.softmax(dim=1)  # we can take the softmax to get the label probabilities

In [23]:
probs

tensor([[3.0281e-04, 1.5533e-02, 1.6785e-03, 9.8247e-01, 1.1703e-05]],
       grad_fn=<SoftmaxBackward0>)

In [24]:
from PIL import Image
import requests

from transformers import CLIPProcessor, CLIPModel

model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

url = "./deer.jpg"
image = Image.open(url)

inputs1 = processor( images=image, return_tensors="pt", padding=True)

In [25]:
from transformers import BatchEncoding

# inputs1.update(inputs)

temp = inputs1
temp.update(inputs)

# print(inputs1)

outputs = model(**temp)
logits_per_image = outputs.logits_per_image  # this is the image-text similarity score
probs = logits_per_image.softmax(dim=1)  # we can take the softmax to get the label probabilities

In [27]:
probs

tensor([[1.8923e-03, 1.4615e-03, 3.5684e-04, 1.7975e-03, 9.9449e-01]],
       grad_fn=<SoftmaxBackward0>)

In [28]:
from PIL import Image
import requests
from transformers import CLIPProcessor, CLIPModel

model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")




dict ={

}

def imgConvertor(image,label):
    image = Image.open(url)
    out = processor( images=image, return_tensors="pt", padding=True)
    dict[label]=out

def similartiyChecker(keyword):
    firstRank=0
    firstRankVal=0

    secondRankVal=0

    thirdRankVal=0

    out = processor(text=[keyword], return_tensors="pt", padding=True)
    for i in dict:  
        
        temp = out.copy()
        temp.update(dict[i])
        outputs = model(**temp)
        logits_per_image = outputs.logits_per_image  # this is the image-text similarity score
        probs = logits_per_image.softmax(dim=1)  # we can take the softmax to get the label probabilities
        print("i: ",probs.item())
        print(probs[0])
        if(probs[0]>firstRank):

            thirdRankVal = secondRankVal
            secondRankVal=firstRankVal

            firstRankVal=i
            firstRank=probs
        
        return firstRank,firstRankVal,secondRankVal,thirdRankVal
    

In [29]:
imgConvertor('deer.jpg','deerImage')
imgConvertor('bird.jpg','birdImage')


In [30]:
print(similartiyChecker('a bird image'))

i:  1.0
tensor([1.], grad_fn=<SelectBackward0>)
(tensor([[1.]], grad_fn=<SoftmaxBackward0>), 'deerImage', 0, 0)


In [31]:
imgConvertor('elder.jpg','elderImage')
imgConvertor('girl.jpg','girlImage')
imgConvertor('hill.jpg','hillImage')

In [32]:
print(similartiyChecker('a old elder man image'))

i:  1.0
tensor([1.], grad_fn=<SelectBackward0>)
(tensor([[1.]], grad_fn=<SoftmaxBackward0>), 'deerImage', 0, 0)


In [33]:
dict.keys()

dict_keys(['deerImage', 'birdImage', 'elderImage', 'girlImage', 'hillImage'])